// Synthetic specimens of every G3 Baustein, with the same content as the
// Paper page `Bausteine · G3` (p-16-0). Used by the golden gallery and the
// Paper diff harness (tool/g3_review.py). Synthetic data only.
import 'g3_format.dart';
import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

import '../training.dart' show OBSportIcon;
import 'charts.dart';
import 'check_in.dart';
import 'chrome.dart';
import 'day.dart';
import 'g3_theme.dart';
import 'metrics.dart';

void _noop() {}

// Paper crops these controls to their 30 pt painted track; the widget keeps
// its full 44 pt touch height in production.
Widget _paperSegmented(OBSegmented child) => Transform.translate(
  offset: const Offset(0, -7),
  child: SizedBox(
    height: 30,
    child: OverflowBox(
      alignment: Alignment.topLeft,
      minHeight: 44,
      maxHeight: 44,
      child: child,
    ),
  ),
);

const _erholung = G3Scale(
  min: 0,
  max: 100,
  band: (58, 80),
  median: 68,
  ticks: [
    G3Tick(0, '0'),
    G3Tick(58, '58', strong: true),
    G3Tick(80, '80', strong: true),
    G3Tick(100, '100'),
  ],
);

const _hr = <(double, double)>[
  (0.0, 121.8),
  (0.5, 123.8),
  (1.0, 126.9),
  (1.5, 125.8),
  (2.0, 127.0),
  (2.5, 128.4),
  (3.0, 127.6),
  (3.5, 130.1),
  (4.0, 131.6),
  (4.5, 132.8),
  (5.0, 130.2),
  (5.5, 132.1),
  (6.0, 132.2),
  (6.5, 136.4),
  (7.0, 136.9),
  (7.5, 135.0),
  (8.0, 140.1),
  (8.5, 140.5),
  (9.0, 139.7),
  (9.5, 140.5),
  (10.0, 139.5),
  (10.5, 139.9),
  (11.0, 143.1),
  (11.5, 142.1),
  (12.0, 143.6),
  (12.5, 144.9),
  (13.0, 144.9),
  (13.5, 147.3),
  (14.0, 147.7),
  (14.5, 150.5),
  (15.0, 150.1),
  (15.5, 151.1),
  (16.0, 151.0),
  (16.5, 152.7),
  (17.0, 152.8),
  (17.5, 151.5),
  (18.0, 154.2),
  (18.5, 155.2),
  (19.0, 155.5),
  (19.5, 155.4),
  (20.0, 154.2),
  (20.5, 154.3),
  (21.0, 155.1),
  (21.5, 154.6),
  (22.0, 158.2),
  (22.5, 156.6),
  (23.0, 158.5),
  (23.5, 157.0),
  (24.0, 160.0),
  (24.5, 161.0),
  (25.0, 158.8),
  (25.5, 161.2),
  (26.0, 165.8),
  (26.5, 165.4),
  (27.0, 169.1),
  (27.5, 168.0),
  (28.0, 168.1),
  (28.5, 173.1),
  (29.0, 176.0),
  (29.5, 172.0),
  (30.0, 169.2),
  (30.5, 167.8),
  (31.0, 168.0),
  (31.5, 163.1),
  (32.0, 156.3),
  (32.5, 154.4),
  (33.0, 151.2),
  (33.5, 148.6),
  (34.0, 149.3),
  (34.5, 145.1),
  (35.0, 145.3),
  (35.5, 143.8),
  (36.0, 141.6),
  (36.5, 143.0),
  (37.0, 139.4),
  (37.5, 141.1),
  (38.0, 138.3),
  (38.5, 138.7),
  (39.0, 136.7),
  (39.5, 136.5),
  (40.0, 139.1),
  (40.5, 137.8),
  (41.0, 135.1),
  (41.5, 137.7),
  (42.0, 136.0),
];
const _d30 = <double?>[
  66,
  62,
  65,
  72,
  65,
  67,
  68,
  64,
  62,
  70,
  75,
  null,
  null,
  null,
  70,
  71,
  64,
  64,
  67,
  69,
  72,
  66,
  64,
  66,
  55,
  62,
  71,
  49,
  63,
  74,
];
const _d90 = <double?>[
  67,
  66,
  62,
  68,
  62,
  64,
  70,
  64,
  66,
  68,
  63,
  63,
  67,
  67,
  70,
  65,
  63,
  60,
  62,
  69,
  70,
  73,
  70,
  72,
  66,
  64,
  67,
  70,
  69,
  64,
  62,
  60,
  60,
  66,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  62,
  69,
  64,
  66,
  62,
  65,
  71,
  66,
  61,
  58,
  61,
  58,
  56,
  59,
  67,
  66,
  66,
  68,
  63,
  66,
  62,
  65,
  72,
  65,
  67,
  68,
  64,
  62,
  70,
  75,
  null,
  null,
  null,
  70,
  71,
  64,
  64,
  67,
  69,
  72,
  66,
  64,
  66,
  55,
  62,
  71,
  49,
  63,
  74,
];

const _hyp = [
  ('W', 5),
  ('L', 20),
  ('T', 35),
  ('L', 40),
  ('R', 15),
  ('L', 30),
  ('T', 25),
  ('L', 35),
  ('W', 4),
  ('R', 25),
  ('L', 40),
  ('T', 8),
  ('L', 30),
  ('R', 30),
  ('W', 6),
  ('L', 32),
  ('R', 28),
  ('L', 20),
  ('R', 25),
  ('W', 11),
];

List<OBStageSegment> _segments() {
  var t = 0.0;
  return [
    for (final (s, m) in _hyp)
      OBStageSegment(
        switch (s) {
          'W' => OBStage.wake,
          'R' => OBStage.rem,
          'L' => OBStage.light,
          _ => OBStage.deep,
        },
        t,
        t += m,
      ),
  ];
}

List<OBTrendMark> _marks(List<double?> v, double lo, double hi) => [
  for (final x in v)
    x == null
        ? OBTrendMark.none
        : (x < lo
              ? OBTrendMark.worse
              : (x > hi ? OBTrendMark.better : OBTrendMark.none)),
];

class _Run extends StatelessWidget {
  const _Run();
  @override
  Widget build(BuildContext context) =>
      OBSportIcon('run', size: 24, color: G3.of(context).ink);
}

/// Paper layer name → specimen.
final Map<String, Widget Function()> g3Specimens = {
  'OBLeadMetric.normal': () => const OBLeadMetric(
    label: 'ERHOLUNG',
    note: 'normal 58–80',
    state: OBLeadState.normal,
    value: 74,
    delta: '6',
    caption: 'über deinem Median 68',
    scale: _erholung,
  ),
  'OBLeadMetric.better': () => const OBLeadMetric(
    label: 'ERHOLUNG',
    note: 'normal 58–80',
    state: OBLeadState.better,
    value: 86,
    delta: '18',
    caption: 'über deinem Normalbereich',
    scale: _erholung,
  ),
  'OBLeadMetric.worse': () => const OBLeadMetric(
    label: 'ERHOLUNG',
    note: 'normal 58–80',
    state: OBLeadState.worse,
    value: 41,
    delta: '27',
    deltaUp: false,
    caption: 'unter deinem Normalbereich',
    scale: _erholung,
  ),
  'OBLeadMetric.plain': () => const OBLeadMetric(
    label: 'HRV',
    note: 'Basis im Aufbau',
    state: OBLeadState.plain,
    value: 48,
    unit: 'ms',
    basisChip: 'kein Normalbereich',
    caption: 'Einordnung ab Nacht 14',
    scale: G3Scale(
      min: 20,
      max: 80,
      ticks: [G3Tick(20, '20'), G3Tick(80, '80 ms')],
    ),
  ),
  'OBLeadMetric.building': () => const OBLeadMetric(
    label: 'ERHOLUNG',
    note: 'Basis im Aufbau',
    state: OBLeadState.building,
    have: 11,
    need: 14,
    title: 'Noch keine Erholung',
    reason: 'Sie braucht 14 Nächte als Basis.',
  ),
  'OBLeadMetric.missing': () => const OBLeadMetric(
    label: 'ERHOLUNG',
    note: 'Keine Nacht',
    state: OBLeadState.missing,
    title: 'Keine Erholung für heute',
  ),
  'OBSecondaryMetric.goal': () => const OBSecondaryMetric(
    label: 'SCHLAF',
    value: '7h18',
    aside: '−27 Min.',
    fill: .73,
    goal: (.775, 'Ziel 7h45'),
    start: '0 h',
    end: '10 h',
  ),
  'OBSecondaryMetric.plain': () => const OBSecondaryMetric(
    label: 'BELASTUNG',
    value: '9,4',
    aside: 'läuft',
    fill: 9.4 / 21,
    start: '0',
    end: '21',
  ),
  'OBSecondaryMetric.missing': () => const OBSecondaryMetric(
    label: 'SCHLAF',
    value: null,
    aside: 'keine Nacht',
    goal: (.775, 'Ziel 7h45'),
    start: '0 h',
    end: '10 h',
  ),
  'OBBodyRow.range': () => const OBBodyRow(
    state: OBBodyState.range,
    name: 'HRV',
    value: '48',
    unit: 'ms',
    at: 48,
    min: 30,
    max: 60,
    band: (38, 52),
    minLabel: '38',
    maxLabel: '52',
  ),
  'OBBodyRow.plain': () => const OBBodyRow(
    state: OBBodyState.plain,
    name: 'HRV',
    value: '48',
    unit: 'ms',
    at: 48,
    min: 30,
    max: 60,
    minLabel: '30',
    maxLabel: '60',
  ),
  'OBBodyRow.building': () => const OBBodyRow(
    state: OBBodyState.building,
    name: 'Atemfrequenz',
    value: '15,8',
    unit: '/min',
    note: 'Basis: noch 3 Nächte',
  ),
  'OBBodyRow.missing': () =>
      const OBBodyRow(state: OBBodyState.missing, name: 'Hauttemperatur'),
  'OBBodyRow.deviation': () => const OBBodyRow(
    state: OBBodyState.deviation,
    name: 'Hauttemperatur',
    value: '+0,4',
    unit: 'zur Basis',
    at: .4,
    min: -1.5,
    max: 1.5,
  ),
  'OBStatRow': () => const OBStatRow([
    ('Ø 30 Tage', '66', null),
    ('Median', '68', null),
    ('Spanne', '49–80', null),
  ]),
  'OBDayValueRow.default': () =>
      const OBDayValueRow(date: 'Mo 28.09', value: '63', share: .63),
  'OBDayValueRow.gap': () => const OBDayValueRow(date: 'So 13.09', value: null),
  'OBChip.delta': () => const OBChip(OBChipKind.delta, '6', up: true),
  'OBChip.better': () => const OBChip(OBChipKind.better, '18', up: true),
  'OBChip.worse': () => const OBChip(OBChipKind.worse, '27', up: false),
  'OBChip.tag': () => const OBChip(OBChipKind.tag, 'auto-erkannt'),
  'OBChip.basis': () =>
      const OBChip(OBChipKind.basis, 'noch kein Normalbereich'),

  'OBPageHeader.hub': () => const OBPageHeader.hub(
    title: 'Heute',
    subtitle: 'Dienstag, 29. September',
    band: OBBandCapsule(state: OBBandState.live, battery: 64),
  ),
  'OBPageHeader.detail': () => const OBPageHeader.detail(
    title: 'ERHOLUNG',
    subtitle: 'Dienstag, 29. September',
    backLabel: 'Heute',
    onBack: null,
  ),
  'OBPageHeader.compact': () => const OBPageHeader.compact(
    title: 'Heute',
    subtitle: 'Di 29.09 · Synthetische Daten',
    band: OBBandCapsule(state: OBBandState.live, battery: 64, small: true),
  ),
  'OBPageHeader.modal': () =>
      const OBPageHeader.modal(title: 'NACHTRAGEN', onBack: _noop),
  'OBBandCapsule.live': () =>
      const OBBandCapsule(state: OBBandState.live, battery: 64),
  'OBBandCapsule.off': () => const OBBandCapsule(state: OBBandState.off),
  'OBBandCapsule.none': () => const OBBandCapsule(state: OBBandState.none),
  'OBIconButton': () =>
      const OBIconButton(icon: LucideIcons.user, label: 'Profil'),
  'OBSyncState.live': () => const OBSyncState(
    kind: OBSyncKind.live,
    text: 'Daten bis 09:38 · Nacht lückenlos',
    synthetic: true,
    onTap: _noop,
  ),
  'OBSyncState.partial': () => const OBSyncState(
    kind: OBSyncKind.partial,
    text: 'Daten bis 09:38 · Nacht mit Lücke',
    synthetic: true,
    onTap: _noop,
  ),
  'OBSyncState.stale': () => const OBSyncState(
    kind: OBSyncKind.stale,
    text: 'Getrennt · Daten bis gestern 23:10',
    synthetic: true,
    onTap: _noop,
  ),
  'OBSyncState.never': () => const OBSyncState(
    kind: OBSyncKind.never,
    text: 'Noch kein Band verbunden',
    synthetic: true,
    onTap: _noop,
  ),
  'OBSyncState.past': () => const OBSyncState(
    kind: OBSyncKind.past,
    text: 'Gespeicherter Tag · Daten bis 23:58',
    synthetic: true,
    onTap: _noop,
  ),
  'OBPanel.hero': () => OBPanel(
    hero: true,
    child: Builder(
      builder: (c) => Text(
        'Inhalt',
        style: G3
            .of(c)
            .t(12, 16, weight: FontWeight.w500, color: G3.of(c).muted),
      ),
    ),
  ),
  'OBPanel': () => OBPanel(
    child: Builder(
      builder: (c) => Text(
        'Inhalt',
        style: G3
            .of(c)
            .t(12, 16, weight: FontWeight.w500, color: G3.of(c).muted),
      ),
    ),
  ),
  'OBDayNote.action': () => const OBDayNote(
    state: OBNoteState.action,
    headline: 'Gut erholt. Heute früher ins Bett.',
    reason: 'Erholung über Median, Schlaf 27 Min. unter Ziel.',
    actionTitle: '22:20 ins Bett',
    actionSubtitle: 'für 8h05 Schlafbedarf bis 06:54',
  ),
  'OBDayNote.reminded': () => const OBDayNote(
    state: OBNoteState.reminded,
    headline: 'Gut erholt. Heute früher ins Bett.',
    reason: 'Erholung über Median, Schlaf 27 Min. unter Ziel.',
    actionTitle: 'Erinnerung um 22:05',
    actionSubtitle: '15 Min. vor 22:20 · abbestellen',
  ),
  'OBDayNote.text': () => const OBDayNote(
    state: OBNoteState.text,
    headline: 'Gut erholt. Heute früher ins Bett.',
    reason: 'Erholung über Median, Schlaf 27 Min. unter Ziel.',
  ),
  'OBDayNote.absent': () => const OBDayNote(
    state: OBNoteState.absent,
    headline: 'Heute keine Notiz',
    reason: 'Ihr fehlt die Nacht. Sie erscheint, wenn alle Werte da sind.',
  ),
  'OBDayNote.sleep': () => const OBDayNote(
    state: OBNoteState.text,
    heading: 'FÜR DIE NACHT',
    headline: 'Heute früher ins Bett.',
    reason: 'Dein Schlafbedarf liegt über deinem Ziel.',
  ),
  'OBActivityRow.auto': () => const OBActivityRow(
    pictogram: _Run(),
    title: 'Lauf',
    subtitle: '07:58–08:40 · 42 Min.',
    unconfirmed: true,
    strain: '+6,1',
  ),
  'OBActivityRow.confirmed': () => const OBActivityRow(
    pictogram: _Run(),
    title: 'Lauf',
    subtitle: '07:58–08:40 · 42 Min.',
    strain: '+6,1',
    zoneMinutes: [0, 4, 19, 16, 3],
  ),
  'OBActivityRow.compact': () => const OBActivityRow(
    pictogram: _Run(),
    title: 'Lauf',
    subtitle: 'Di 29.09 · 42 Min.',
    compact: true,
    onTap: _noop,
  ),
  'OBActivityRow.confirmation': () => const OBActivityRow(
    pictogram: _Run(),
    title: 'Lauf',
    subtitle: '07:58–08:40 · 42 Min.',
    unconfirmed: true,
    strain: '+6,1',
    confirmationFooter: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Sportart richtig?'),
        OBActionSecondary('Stimmt', onPressed: _noop),
      ],
    ),
  ),
  'OBCheckIn.shared': () => const OBCheckIn(
    title: 'Alkohol am Abend?',
    index: 2,
    total: 4,
    target: 'zu gestern Abend',
    answer: Row(
      children: [
        Expanded(child: OBActionSecondary('Nein', onPressed: _noop)),
        SizedBox(width: 8),
        Expanded(child: OBActionSecondary('Ja', onPressed: _noop)),
      ],
    ),
    onLater: _noop,
  ),
  'OBSegmented.week': () => _paperSegmented(
    const OBSegmented(items: ['Erholung', 'Schlaf', 'Belastung'], selected: 0),
  ),
  'OBSegmented.week.sleep': () => _paperSegmented(
    const OBSegmented(
      items: ['Erholung', 'Schlaf', 'Belastung'],
      selected: 1,
      disabled: {0},
    ),
  ),
  'OBWeekBars.recovery': () => OBWeekBars(
    max: 111,
    band: (58, 80),
    bars: [
      for (final (i, (d, v)) in [
        ('Mi', 66),
        ('Do', 55),
        ('Fr', 62),
        ('Sa', 71),
        ('So', 49),
        ('Mo', 63),
        ('Heute', 74),
      ].indexed)
        OBWeekBar(
          d,
          v.toDouble(),
          label: '$v',
          deviation: v < 58 ? G3Deviation.worse : G3Deviation.none,
          today: i == 6,
        ),
    ],
    footer: const [
      G3Legend.band('dein Normalbereich 58–80'),
      G3Legend.mark('2 Tage darunter', G3Deviation.worse),
    ],
  ),
  'OBWeekBars.sleep': () => OBWeekBars(
    max: 111 / 11 * 60,
    goal: 465,
    labelsBelow: true,
    bars: [
      for (final (i, (d, m)) in [
        ('Mi', 422),
        ('Do', 391),
        ('Fr', 460),
        ('Sa', 485),
        ('So', 372),
        ('Mo', 445),
        ('Heute', 438),
      ].indexed)
        OBWeekBar(d, m.toDouble(), label: g3Duration(m), today: i == 6),
    ],
    footer: const [
      G3Legend.goal('Ziel 7h45'),
      G3Legend.text('Erholung: noch keine Werte'),
    ],
  ),
  'OBWeekBars.empty': () => OBWeekBars(
    max: 111,
    emptyReason: 'Erholung braucht 14 Nächte · noch 3',
    bars: [
      for (final (i, d) in [
        'Mi',
        'Do',
        'Fr',
        'Sa',
        'So',
        'Mo',
        'Heute',
      ].indexed)
        OBWeekBar(d, null, today: i == 6),
    ],
    footer: const [
      G3Legend.text('Keine Werte erfunden'),
      G3Legend.text('Schlaf zeigen ›'),
    ],
  ),
  'OBNightCard.full': () => OBNightCard(
    state: OBNightState.full,
    note: 'lückenlos',
    asleep: '7h18',
    subtitle: 'Schlaf von 7h44 im Bett',
    segments: _segments(),
    totalMinutes: 464,
    axis: ('23:10', '03:00', '06:54'),
    totals: const [
      (OBStage.deep, '1h08'),
      (OBStage.light, '4h07'),
      (OBStage.rem, '2h03'),
      (OBStage.wake, '26 Min.'),
    ],
  ),
  'OBNightCard.gap': () => OBNightCard(
    state: OBNightState.gap,
    note: '48 Min. Lücke',
    asleep: '6h31',
    subtitle: 'gezählt in 6h56 mit Daten',
    segments: _segments(),
    totalMinutes: 464,
    gaps: const [(171, 219)],
    gapNote: '02:01–02:49 ohne Daten · nicht aufgefüllt',
    axis: ('23:10', '03:00', '06:54'),
    totals: const [
      (OBStage.deep, '55 Min.'),
      (OBStage.light, '3h45'),
      (OBStage.rem, '1h51'),
      (OBStage.wake, '25 Min.'),
    ],
  ),
  'OBNightCard.missing': () => const OBNightCard(state: OBNightState.missing),
  'OBSectionHeader': () => Transform.translate(
    offset: const Offset(-.5, -1),
    child: const OBSectionHeader(
      'AKTIVITÄT',
      action: 'Eintragen',
      onAction: _noop,
    ),
  ),
  'OBSectionHeader.plain': () => const OBSectionHeader('WOCHE'),
  'OBSectionHeader.detail': () => const Padding(
    padding: EdgeInsets.symmetric(horizontal: 16),
    child: OBSectionHeader.detail('MESSWERTE', trailing: Text('3')),
  ),
  'G3DetailPage.section': () => const SizedBox(
    height: 180,
    child: G3DetailPage(
      header: OBPageHeader.detail(
        title: 'DETAIL',
        backLabel: 'Heute',
        onBack: _noop,
      ),
      fullWidthSection: OBSectionHeader('VERLAUF'),
      children: [Text('Werte für diesen Tag')],
    ),
  ),
  'OBListRow.default': () => const OBListRow(
    icon: LucideIcons.route,
    title: 'Strecke hinzufügen',
    subtitle: 'Das Band misst keine Strecke und kein Tempo.',
  ),
  'OBListRow.value': () => const OBListRow(
    icon: LucideIcons.scale,
    title: 'Gewicht',
    subtitle: 'manuell · 27.09',
    value: '78,4 kg',
  ),
  'OBActionPrimary': () => const OBActionPrimary('Speichern'),
  'OBActionSecondary': () => const OBActionSecondary('Abbrechen'),
  'OBPillButton': () => const OBPillButton('Ziel festlegen'),
  'OBSegmented': () => _paperSegmented(
    const OBSegmented(items: ['Manuell', 'Apple Health'], selected: 0),
  ),
  'OBSegmented.range': () => _paperSegmented(
    const OBSegmented(items: ['7 T', '30 T', '90 T'], selected: 0),
  ),
  'OBSheet': () => OBSheet(
    title: 'Titel des Sheets',
    subtitle: 'Ein Satz, was hier entschieden wird.',
    child: Builder(
      builder: (c) => G3Dashed(
        height: 96,
        radius: 14,
        child: Center(
          child: Text(
            'Inhalt',
            style: G3
                .of(c)
                .t(13, 16, weight: FontWeight.w500, color: G3.of(c).muted),
          ),
        ),
      ),
    ),
  ),
  'OBSheet.independentClose': () => const OBSheet(
    title: 'Sportart',
    onClose: _noop,
    onCancel: _noop,
    child: Text('Auswahl'),
  ),
  'OBEmptyState': () => const OBEmptyState(
    title: 'Noch keine Werte',
    reason: 'Erholung braucht 14 Nächte. Du hast 11.',
    action: 'So entsteht die Basis',
  ),
  'OBErrorBlock': () => const OBErrorBlock(
    title: 'Übertragung unterbrochen',
    reason:
        'Das Band hat um 07:12 die Verbindung verloren. Gespeicherte Daten bleiben erhalten.',
    secondaryLabel: 'Details',
  ),
  'OBHrTrace': () => const OBHrTrace(
    samples: _hr,
    duration: 42,
    gaps: [(21.0, 21.67)],

    average: '148',
    peak: '176',
    axis: ('07:58', '08:19', '08:40'),
    gapLabel: '40 s ohne Signal',
    signalShare: '96 %',
    signalSegments: [(1260, false), (40, true), (1220, false)],
  ),
  'OBZoneRows': () => const OBZoneRows(
    domain: G3Domain.load,
    ranges: ['90–100 %', '80–90 %', '70–80 %', '60–70 %', '50–60 %'],
    zones: [
      OBZone(5, '90–100 %', 3),
      OBZone(4, '80–90 %', 16),
      OBZone(3, '70–80 %', 19),
      OBZone(2, '60–70 %', 4),
      OBZone(1, '50–60 %', 0),
    ],
    source: 'HFmax 186 · geschätzt aus Alter',
    onBasis: _noop,
  ),
  'OBTrendChart.d7': () => OBTrendChart(
    title: 'ERHOLUNG',
    period: OBTrendPeriod.d7,
    values: const [66, 55, 62, 71, 49, 63, 74],
    marks: _marks(const [66, 55, 62, 71, 49, 63, 74], 58, 80),
    min: 0,
    max: 100,
    band: (58, 80),
    bandLabels: ('58', '80'),
    xLabels: const ['Mi', 'Do', 'Fr', 'Sa', 'So', 'Mo', 'Heute'],
    footLeft: 'Ø 63 · Median 68 · 2 Tage darunter',
    footRight: '7 von 7 Tagen',
  ),
  'OBTrendChart.d30': () => OBTrendChart(
    title: 'ERHOLUNG',
    period: OBTrendPeriod.d30,
    values: _d30,
    marks: _marks(_d30, 58, 80),
    min: 30,
    max: 100,
    band: (58, 80),
    bandLabels: ('58', '80'),
    xLabels: const ['31.08', '14.09', 'heute'],
    footLeft: 'Ø 66 · 2 Tage darunter · 3 Lücken',
    footRight: '27 von 30 Tagen',
  ),
  'OBTrendChart.d90': () => OBTrendChart(
    title: 'ERHOLUNG',
    period: OBTrendPeriod.d90,
    values: _d90,
    marks: _marks(_d90, 58, 80),
    min: 30,
    max: 100,
    band: (58, 80),
    bandLabels: ('58', '80'),
    xLabels: const ['02.07', '15.08', 'heute'],
    footLeft: 'Ø 65 · 3 Tage darunter · 10 Lücken',
    footRight: '80 von 90 Tagen',
  ),
  'OBCardHeader': () => const OBCardHeader('KÖRPER', note: 'vergangene Nacht'),
  'OBStepsCard.default': () => OBStepsCard(
    total: 6480,
    note: 'Zähler im Band · bis 09:38',
    hourly: [
      for (var h = 0; h < 10; h++) const {7: 820, 8: 4630, 9: 1030}[h] ?? 0,
    ],
  ),
  'OBStepsCard.missing': () =>
      const OBStepsCard(total: null, note: 'Zähler im Band'),
  'OBFooterStamp': () => const OBFooterStamp(
    'Letzter Bandwert 09:38 · Übertragung 09:38',
    synthetic: true,
  ),
  'OBDateStrip': () => const OBDateStrip(
    days: [
      ('Mi', '23'),
      ('Do', '24'),
      ('Fr', '25'),
      ('Sa', '26'),
      ('So', '27'),
      ('Mo', '28'),
      ('Di', '29'),
    ],
    selected: 4,
  ),
  'OBFormField.number': () => OBFormField.number(
    label: 'GEWICHT',
    controller: TextEditingController(text: '78,4'),
    unit: 'kg',
    when: 'Di 29.09 · 07:05',
    onTime: _noop,
  ),
};
